#ifndef NFC_BOARDSELECTION_H
#define NFC_BOARDSELECTION_H

#include "nfc/config.h"

#define PHDRIVER_PIN_SSEL PIN_SSEL
#define PHDRIVER_PIN_RESET PIN_RESET
#define PHDRIVER_PIN_IRQ PIN_IRQ
#define PHDRIVER_PIN_BUSY PIN_BUSY
#define PHDRIVER_PIN_DWL PIN_DWL

#define PIN_IRQ_TRIGGER_TYPE PH_DRIVER_INTERRUPT_RISINGEDGE

#define PHDRIVER_PIN_NSS_PULL_CFG PH_DRIVER_PULL_UP
#define PHDRIVER_PIN_RESET_PULL_CFG PH_DRIVER_PULL_UP
#define PHDRIVER_PIN_IRQ_PULL_CFG PH_DRIVER_PULL_UP
#define PHDRIVER_PIN_BUSY_PULL_CFG PH_DRIVER_PULL_UP
#define PHDRIVER_PIN_DWL_PULL_CFG PH_DRIVER_PULL_UP

#define PH_DRIVER_SET_LOW 0
#define PH_DRIVER_SET_HIGH 1
#define RESET_POWERDOWN_LEVEL PH_DRIVER_SET_LOW
#define RESET_POWERUP_LEVEL PH_DRIVER_SET_HIGH

#endif /* NFC_BOARDSELECTION_H */

